# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 582a4628515a154a89a64f91176e73bde0794d5848fcf2ef56124ffbc9f56e1e6989a4f16cb8b65c640f253bad1ad5ed157893f52fcd290c72ac837f2ee2f267

test:
  secret_key_base: ee752db82454524e2325c0af1671100ebf526e94fae73542f773cd3f1055ae94572aabed996593579126669183c6a08eaa2b0e75af9ecd280fda1ca3253b9122

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
